%Facts

%Rules
holiday(X, 'Tempat') :- personality(X, 'ISTJ'), cost(X, 'Mampu')
holiday(X, 'Tempat') :- personality(X, 'ISTP'), cost(X, 'Mampu')
holiday(X, 'Tempat') :- personality(X, 'ISFP'), cost(X, 'Mampu')
holiday(X, 'Tempat') :- personality(X, 'ISFP'), cost(X, 'Mampu')
holiday(X, 'Tempat') :- personality(X, 'INTJ'), cost(X, 'Mampu')
holiday(X, 'Tempat') :- personality(X, 'INTP'), cost(X, 'Mampu')
holiday(X, 'Tempat') :- personality(X, 'INFJ'), cost(X, 'Mampu')
holiday(X, 'Tempat') :- personality(X, 'INFP'), cost(X, 'Mampu')
holiday(X, 'Tempat') :- personality(X, 'ESTJ'), cost(X, 'Mampu')
holiday(X, 'Tempat') :- personality(X, 'ESTP'), cost(X, 'Mampu')
holiday(X, 'Tempat') :- personality(X, 'ESFJ'), cost(X, 'Mampu')
holiday(X, 'Tempat') :- personality(X, 'ESFP'), cost(X, 'Mampu')
holiday(X, 'Tempat') :- personality(X, 'ENTJ'), cost(X, 'Mampu')
holiday(X, 'Tempat') :- personality(X, 'ENTP'), cost(X, 'Mampu')
holiday(X, 'Tempat') :- personality(X, 'ENFJ'), cost(X, 'Mampu')
holiday(X, 'Tempat') :- personality(X, 'ENFP'), cost(X, 'Mampu')

holiday(X, 'Tempat') :- personality(X, 'ISTJ'), cost(X, 'Cukup')
holiday(X, 'Tempat') :- personality(X, 'ISTP'), cost(X, 'Cukup')
holiday(X, 'Tempat') :- personality(X, 'ISFP'), cost(X, 'Cukup')
holiday(X, 'Tempat') :- personality(X, 'ISFP'), cost(X, 'Cukup')
holiday(X, 'Tempat') :- personality(X, 'INTJ'), cost(X, 'Cukup')
holiday(X, 'Tempat') :- personality(X, 'INTP'), cost(X, 'Cukup')
holiday(X, 'Tempat') :- personality(X, 'INFJ'), cost(X, 'Cukup')
holiday(X, 'Tempat') :- personality(X, 'INFP'), cost(X, 'Cukup')
holiday(X, 'Tempat') :- personality(X, 'ESTJ'), cost(X, 'Cukup')
holiday(X, 'Tempat') :- personality(X, 'ESTP'), cost(X, 'Cukup')
holiday(X, 'Tempat') :- personality(X, 'ESFJ'), cost(X, 'Cukup')
holiday(X, 'Tempat') :- personality(X, 'ESFP'), cost(X, 'Cukup')
holiday(X, 'Tempat') :- personality(X, 'ENTJ'), cost(X, 'Cukup')
holiday(X, 'Tempat') :- personality(X, 'ENTP'), cost(X, 'Cukup')
holiday(X, 'Tempat') :- personality(X, 'ENFJ'), cost(X, 'Cukup')
holiday(X, 'Tempat') :- personality(X, 'ENFP'), cost(X, 'Cukup')

personality(X, 'ISTJ') :- IvsE(X, 'I'), SvsN(X, 'S'), TvsF(X, 'T'), JvsP(X, 'J')
personality(X, 'ISTP') :- IvsE(X, 'I'), SvsN(X, 'S'), TvsF(X, 'T'), JvsP(X, 'P')
personality(X, 'ISFJ') :- IvsE(X, 'I'), SvsN(X, 'S'), TvsF(X, 'F'), JvsP(X, 'J')
personality(X, 'ISFP') :- IvsE(X, 'I'), SvsN(X, 'S'), TvsF(X, 'F'), JvsP(X, 'P')
personality(X, 'INTJ') :- IvsE(X, 'I'), SvsN(X, 'N'), TvsF(X, 'T'), JvsP(X, 'J')
personality(X, 'INTP') :- IvsE(X, 'I'), SvsN(X, 'N'), TvsF(X, 'T'), JvsP(X, 'P')
personality(X, 'INFJ') :- IvsE(X, 'I'), SvsN(X, 'N'), TvsF(X, 'F'), JvsP(X, 'J')
personality(X, 'INFP') :- IvsE(X, 'I'), SvsN(X, 'N'), TvsF(X, 'F'), JvsP(X, 'P')
personality(X, 'ESTJ') :- IvsE(X, 'E'), SvsN(X, 'S'), TvsF(X, 'T'), JvsP(X, 'J')
personality(X, 'ESTP') :- IvsE(X, 'E'), SvsN(X, 'S'), TvsF(X, 'T'), JvsP(X, 'P')
personality(X, 'ESFJ') :- IvsE(X, 'E'), SvsN(X, 'S'), TvsF(X, 'F'), JvsP(X, 'J')
personality(X, 'ESFP') :- IvsE(X, 'E'), SvsN(X, 'S'), TvsF(X, 'F'), JvsP(X, 'P')
personality(X, 'ENTJ') :- IvsE(X, 'E'), SvsN(X, 'N'), TvsF(X, 'T'), JvsP(X, 'J')
personality(X, 'ENTP') :- IvsE(X, 'E'), SvsN(X, 'N'), TvsF(X, 'T'), JvsP(X, 'P')
personality(X, 'ENFJ') :- IvsE(X, 'E'), SvsN(X, 'N'), TvsF(X, 'F'), JvsP(X, 'J')
personality(X, 'ENFP') :- IvsE(X, 'E'), SvsN(X, 'N'), TvsF(X, 'F'), JvsP(X, 'P')